local virusConfig = require(script.Parent.Parent.CONFIGs.VirusConfig)
local spreadManager = require(script.Parent.InfectionSpreadManager)

local VirusManager = {}

function VirusManager.Initialize()
	
end

function VirusManager.InfectPlayer(player, virusType)
	
end

function VirusManager.CurePlayer(player)
	
end

function VirusManager.GetInfectionStatus(player)
	
end

function VirusManager.StartIncubation(player)
	
end

function VirusManager.ProgressInfection(player)
	
end

function VirusManager.CreateSymptoms(player)
	
end

function VirusManager.UpdateSymptoms(player, stage)
	
end

function VirusManager.RemoveSymptoms(player)
	
end

function VirusManager.KillInfectedPlayer(player)
	
end

return VirusManager
